// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 0.1.1
//  
//     このファイルの各メソッドにユーザーの実装を加えてください。
//     ファイルを削除しなければ、コードが再生成される事はありません。
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Kae.IoT.Device.Sensors;
using Microsoft.Azure.Devices.Client;

namespace My.Gen.MeasurementInstrumentsEdge
{
    partial class IoTApp : IIoTApp
    {
        public AppDTDesiredProperties DesiredProperties { get; set; }
        public AppDTReporetedProperties ReportedProperties { get; set; }

                public string Start(string payload)
        {
            string result = "";
            Console.WriteLine($"Invoked 'Start' with '{payload}'");
            // TODO: implement direct method logic 
            return result;
        }


                public string Stop(string payload)
        {
            string result = "";
            Console.WriteLine($"Invoked 'Stop' with '{payload}'");
            // TODO: implement direct method logic 
            return result;
        }


        
        
        public async Task ReceivedC2DDataAsync(Message message)
        {
            Console.WriteLine($"Received C2D - {System.Text.Encoding.UTF8.GetString(message.GetBytes())}");
            if (message.Properties.Count > 0) {
                Console.WriteLine("  properties...");
                foreach (var prop in message.Properties)
                {
                    Console.WriteLine($"  {prop.Key}:{prop.Value}");
                }
            }
            // TODO: implment logic when message is received from clou
        }

        public async Task UpdatedDTDesiredPropertiesAsync(AppDTDesiredProperties dp)
        {
            Console.WriteLine($"Updated DT Desired Props - {DesiredProperties.Serialize()}");
            // TODO: implment reconfiguration logic with updated desired properties
        }

        public async Task UserPreInitializeAsync()
        {
            // TODO: impliment initialization logic before connecting to IoT Hub
        }

        public async Task UserPostInitializeAsync()
        {
            // TODO: implement initialization logic after connected to IoT Hub
        }

        public async Task UserPreTerminateAsync()
        {
            // TODO: implement termination logic before disconnecting from IoT Hub
        }

        public async Task UserPostTerminateAsync()
        {
            // TODO: implement termination logic after disconnected from IoT Hub
        }

        public async Task DoWorkAsync()
        {
            // Sample Logic
            await iotClient.UpdateDeviceTwinsReportedPropertiesAsync(ReportedProperties);
            var task = new Task(async () =>
            {
                // Sensor
                var bme280 = new BME280Sensor(1);
                if (!bme280.Initalize())
                {
                    Console.WriteLine("BME280 can't be initialized!");
                }
#if USE_MHZ198
                var mhz198 = new MHZ19BSensor() { Port = "/dev/serial0" };
                if (!mhz198.Initalize())
                {
                    Console.WriteLine("MHZ19B can't be initialized!");
                }
#endif
                var rand = new Random(DateTime.Now.Millisecond);
                var updatingInterval = TimeSpan.FromMilliseconds(1000);
                while (true)
                {
                    // Samples
                    lock (sensingData)
                    {
                        // implement sensing data update logic
                        var measuredData = bme280.Read();
                        foreach (var md in measuredData)
                        {
                            if (md.SensorType == SensorType.Temperature)
                            {
                                sensingData.Environment.Temperature = md.Value;
                            }
                            else if (md.SensorType == SensorType.Humidity)
                            {
                                sensingData.Environment.Humidity = md.Value;
                            }
                            else if (md.SensorType == SensorType.Pressure)
                            {
                                sensingData.Environment.AtmosphericPressure = md.Value;
                            }
                        }
#if USE_MHZ198
                        measuredData = mhz198.Read();
                        foreach (var md in measuredData)
                        {
                            if (md.SensorType == SensorType.CarbonDioxideConcentration)
                            {
                                sensingData.Environment.CO2Concentration = md.Value;
                                break;
                            }
                        }
#else
                        sensingData.Environment.CO2Concentration = 200.0 + rand.NextDouble();
#endif
                        sensingData.Environment.Brightness = 739.2 + rand.NextDouble();
                        sensingData.Environment.MeasuredTime = DateTime.Now;
                    }
                    await iotClient.UpdateD2CDataAsync(sensingData);
                    await Task.Delay(updatingInterval);
                }
            });
            task.Start();
            iotClient.StartSendD2CMessageAsync(TimeSpan.FromSeconds(10), "envOutput");

        }
    }
}
