// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 0.1.1
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------

using Kae.IoT.Framework;
using Kae.Utility.Logging;
using Microsoft.Azure.Devices.Client;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace My.Gen.MeasurementInstrumentsEdge
{
    partial class IoTApp
    {
        private MeasurementInstrumentsEdgeAppConnector appConnector;
        private IoTClient iotClient;

        // Sensing Data can be stored in this variable
        private D2CData sensingData;

        private Logger logger;

        public IoTApp(Logger logger = null)
        {
            this.logger = logger;
            sensingData = new D2CData();
        }

        public D2CData GetD2CData()
        {
            return sensingData;
        }

        public async Task InitializeAsync(string configYamlFile, Logger log)
        {
            DesiredProperties = new AppDTDesiredProperties();
            ReportedProperties = new AppDTReporetedProperties();

            if (logger == null)
            {
                //logger = ConsoleLogger.CreateLogger();
                logger = log;
            }
            try
            {
                var iotAppConfig = IoTAppConfigResolver.ResolveConfig(configYamlFile);
                appConnector = new MeasurementInstrumentsEdgeAppConnector(iotAppConfig, this);
                iotClient = IoTClientFactory.CreateIoTClientForEdge(appConnector, logger);

                await iotClient.OpenAsync();

                logger.LogInfo("Getting DT");
                DesiredProperties = (AppDTDesiredProperties)await iotClient.GetDeviceTwinsDesiredPropertiesAsync(DesiredProperties);
                logger.LogInfo("Updated DT Props");
            }
            catch(Exception ex)
            {
                logger.LogInfo(ex.ToString());
            }
        }


        public async Task TerminateAsync()
        {
            await iotClient.CloseAsync();
        }
    }
}
