# -------------------------------------------------------------------------
# Copyright (c) Knowledge & Experience. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
# --------------------------------------------------------------------------

FROM navikey/raspbian-bullseye

WORKDIR /app

RUN sudo apt-get update
RUN sudo apt-get install -y sense-hat
RUN sudo apt-get install -y python3-pip
RUN pip3 install https://github.com/Azure/azure-iot-sdk-python/releases/download/2022-08-23/azure_iot_device-2.12.0-py3-none-any.whl

COPY . .
CMD [ "python3", "-u", "./app.py" ]
