// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 0.1.1
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Azure.Devices.Client;

namespace BuildingManagement.Gen.MeasurementInstrumentsDevice
{
    interface IIoTApp
    {
        AppDTDesiredProperties DesiredProperties
        {
            get;
            set;
        }

        Task DoWorkAsync(CancellationTokenSource cancellationTokenSource);

                string Start(string payload);
                string Stop(string payload);
        
        
        D2CData GetD2CData();
        Task ReceivedC2DDataAsync(Message data);
        Task UpdatedDTDesiredPropertiesAsync(AppDTDesiredProperties dp);

        Task UserPreInitializeAsync();
        Task UserPostInitializeAsync();
        Task UserPreTerminateAsync();
        Task UserPostTerminateAsync();
    }

}
