FROM navikey/raspbian-bullseye
WORKDIR /app

RUN apt-get upgrade
RUN apt-get update

RUN apt-get -y install python3-pip
RUN python3 --version

RUN pip3 install requests
RUN pip3 install azure-storage-blob
RUN pip3 install https://github.com/Azure/azure-iot-sdk-python/releases/download/2022-08-23/azure_iot_device-2.12.0-py3-none-any.whl

COPY . ./

CMD ["python3",  "-u", "./app.py"]
