FROM ubuntu:20.04
WORKDIR /app

RUN apt-get upgrade
RUN apt-get update

RUN apt-get -y install python3 python3-pip
RUN python3 --version

RUN pip3 install requests
RUN pip3 install azure-iot-device
RUN pip3 install azure-storage-blob

COPY . ./

CMD ["python3",  "-u", "./app.py"]
