FROM navikey/raspbian-bullseye
WORKDIR /app

RUN apt-get upgrade
RUN apt-get update

RUN apt-get -y install python3 python3-dev python3-pip python3-opencv

RUN pip3 install Pillow
RUN pip3 install Flask

COPY . ./

CMD ["python3",  "-u", "./app.py"]
