FROM ubuntu:20.04
WORKDIR /app

RUN mkdir /usr/share/zoneinfo
RUN mkdir /usr/share/zoneinfo/Asia
RUN mkdir /usr/share/zoneinfo/Tokyo
RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

RUN apt-get upgrade
RUN apt-get update

# ENV DEBIAN_FRONTEND nointeractive
RUN apt-get -y install python3 python3-dev python3-pip python3-opencv

RUN pip3 install Pillow
RUN pip3 install Flask

COPY . ./

CMD ["python3",  "-u", "./app.py"]
